### ISSUE TITLE
Worker not found and Unexpected usage at EditorSimpleWorker.loadForeignModule

### ISSUE THREAD

**Issue by 9teMare** [DTStack/monaco-sql-languages#27]
我的Wepack是在`vue.config.js`里配置的：
My Webpack is configured in `vue.config.js`:
```js
module.exports = {
  configureWebpack: {
    entry: {
      'sparksql.worker':
        'monaco-sql-languages/out/esm/sparksql/sparksql.worker.js',
      'sql.worker': 'monaco-sql-languages/out/esm/sql/sql.worker.js',
    }
  }
}
```

在封装的`monaco-editor`组件中：
Inside my monaco-editor component:
```js
import * as monaco from 'monaco-editor';
import 'monaco-sql-languages/out/esm/sparksql/sparksql.contribution';
import 'monaco-sql-languages/out/esm/sql/sql.contribution';

MonacoEnvironment = {
  getWorkerUrl: function (moduleId, label) {
    console.log(moduleId, label);
    switch (label) {
      case 'sparksql': {
        return './sparksql.worker.js';
      }
      default: {
        return './editor.worker.js';
      }
    }
  },
};
```

可是项目跑起来后报错:
But I get the following error in the console:
```
GET http://localhost:3000/xxx/sparksql.worker.js 404 (Not Found)
GET http://localhost:3000/xxx/editor.worker.js 404 (Not Found)
Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:460:1)
    at eval (webWorker.js:38:1)
```

以下是部分`package.json`
Here is part of my `package.json`
```json
"dt-sql-parser": "^4.0.0-beta.3.2",
"monaco-editor": "0.33",
"monaco-editor-webpack-plugin": "^7.0.1",
"monaco-sql-languages": "^0.11.0",
"webpack": "5.61.0",
```

这个应该怎么解决呢？
How can I resolve this?

**Comment by wewoor** [comment]
@9teMare 抱歉，才回复，需要注意下 output 的配置，可以参考下：https://github.com/DTStack/monaco-sql-languages/blob/e31630f73043135f6db16bdac7b037ef8a14cb52/scripts/webpack.base.js#L22

**Comment by HaydenOrz** [comment]
Inactive issue
