### ISSUE TITLE
cannot read properties of undefined

### ISSUE THREAD

**Issue by Samrose-Ahmed** [DTStack/monaco-sql-languages#75]
I'm getting this error trying to use with trinosql:

```
TypeError: Cannot read properties of undefined (reading 'get')
    at _CodeCompletionCore.collectCandidates (http://localhost:3000/trinosql.worker.js:68773:33)
    at TrinoSQL.getSuggestionAtCaretPosition (http://localhost:3000/trinosql.worker.js:50222:29)
    at TrinoSQLWorker.<anonymous> (http://localhost:3000/trinosql.worker.js:63071:41)
    at Generator.next (<anonymous>)
    at http://localhost:3000/trinosql.worker.js:63030:67
    at new Promise (<anonymous>)
    at __awaiter (http://localhost:3000/trinosql.worker.js:63012:10)
    at TrinoSQLWorker.doComplete (http://localhost:3000/trinosql.worker.js:63068:12)
    at EditorSimpleWorker.fmr (http://localhost:3000/trinosql.worker.js:61720:58)
    at SimpleWorkerServer._handleMessage (http://localhost:3000/trinosql.worker.js:58454:59)
```

**Comment by Samrose-Ahmed** [comment]
Seems to be throwing here https://github.com/DTStack/dt-sql-parser/blob/55379f3cf5a88ae7682d2a9d1a08a509e73c1263/src/parser/common/basicParser.ts#L330 inside because the tokenStream is undefined.

**Comment by HaydenOrz** [comment]
Please provide the SQL content and the version you have installed, so that we can locate the problem more quickly

**Comment by Samrose-Ahmed** [comment]
This is one the latest version and happens with any contact from single character to full sql string

**Comment by Samrose-Ahmed** [comment]
I tried changing to a few versions earlier and issue is they as well

**Comment by HaydenOrz** [comment]
This problem should be caused by the version update of antlr4-c3. See this [issue ](https://github.com/mike-lischke/antlr4-c3/issues/90). If the version of antlr4-c3 in the node_modules is above 3.2.x, you can confirm that this issue is causing it. We will release a new version as soon as possible to fix this issue.

**Comment by Samrose-Ahmed** [comment]
Thanks much for the update. I can confirm the antlr4-c3 version is `3.3.4`. I will try overriding it now.

**Comment by Samrose-Ahmed** [comment]
can confirm it works by downgrading to 3.1.1

**Comment by HaydenOrz** [comment]
Refer to  https://github.com/DTStack/dt-sql-parser/issues/206.

**Comment by HaydenOrz** [comment]
@Samrose-Ahmed  
Sorry for the trouble!
Now the new version `v0.12.0-beta.6`  has been released.  If you confirm that your issue has been resolved, please close this issue, or we will close it in a week.

**Comment by Samrose-Ahmed** [comment]
I can confirm issue is resolved thanks.
